// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chirpy.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createChirpy = `-- name: CreateChirpy :one
INSERT INTO chirpy (id, body,  created_at, updated_at, user_id)
VALUES (
  gen_random_uuid(), 
	$1, 
	NOW(), 
	NOW(), 
	$2
	
)
RETURNING id, body, created_at, updated_at, user_id
`

type CreateChirpyParams struct {
	Body   sql.NullString
	UserID uuid.NullUUID
}

func (q *Queries) CreateChirpy(ctx context.Context, arg CreateChirpyParams) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, createChirpy, arg.Body, arg.UserID)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getChirpyByID = `-- name: GetChirpyByID :one
SELECT id, body, created_at, updated_at, user_id FROM chirpys WHERE id = $1
`

func (q *Queries) GetChirpyByID(ctx context.Context, id uuid.UUID) (Chirpy, error) {
	row := q.db.QueryRowContext(ctx, getChirpyByID, id)
	var i Chirpy
	err := row.Scan(
		&i.ID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getChirpys = `-- name: GetChirpys :many
SELECT id, body, created_at, updated_at, user_id FROM chirpy
`

func (q *Queries) GetChirpys(ctx context.Context) ([]Chirpy, error) {
	rows, err := q.db.QueryContext(ctx, getChirpys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chirpy
	for rows.Next() {
		var i Chirpy
		if err := rows.Scan(
			&i.ID,
			&i.Body,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
